F90FLAGS += -I../../src
LDFLAGS = -ldftatom -L../../src

export LDFLAGS

all:
	$(MAKE) -C lda -f Makefile.manual
	$(MAKE) -C rlda -f Makefile.manual
	$(MAKE) -C atom_U -f Makefile.manual

test:
	$(MAKE) -C lda -f Makefile.manual test
	$(MAKE) -C rlda -f Makefile.manual test
	$(MAKE) -C atom_U -f Makefile.manual test

clean:
	$(MAKE) -C lda -f Makefile.manual clean
	$(MAKE) -C rlda -f Makefile.manual clean
	$(MAKE) -C atom_U -f Makefile.manual clean
